### ISSUE TITLE
Setup the project with postgresql in Heroku

### ISSUE THREAD

**Issue by mariocesar** [mariocesar/calenguay#1]
See https://devcenter.heroku.com/articles/django-app-configuration

Please make sure it doesn't change the already working media/static configuration, just setup the database settings.

**Comment by jokedetone** [comment]
# Configure Django App for Heroku.
import django_heroku
django_heroku.settings(locals(), staticfiles=False)


import dj_database_url
DATABASES['default'] = dj_database_url.config(conn_max_age=600, ssl_require=True)
